## Basic Configuration

baseurl = "http://blakebraun.com" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"
googleAnalytics = "UA-89170054-1"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Blake Braun"
title = "Blake Braun"

theme = "hugo-goa"

##blackfriday (allows for link opening in separate window)
[blackfriday]
hrefTargetBlank = true

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Blake Braun"
intro = "Aspiring Technical & Creative Professional"
description = "Computer Science and Communication student at [Saint Louis University](http://slu.edu)"
authorImage = "profile.jpg"
dateFormat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Blake Braun, Aspiring Technical & Creative Professional"
keywords = "student,professional,technical,creative,developer"

## Social Accounts
[params.social]
github = "blakebraun"
linkedIn = "bbraun5"
email = "blake@blakebraun.com"

## Extras
[params.extra]
copyright = "© 2016. Blake Braun. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredBy = true
hightlightJS = true

## Main Menu
[[menu.main]]
    name = "about"
    weight = 100
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "my work"
    identifier = "my work"
    weight = 200
    url = "/work/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 300
    url = "/contact/"
